name: Flutter CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON_ENC }}
      GOOGLE_SERVICES_INFO_PLIST: ${{ secrets.GOOGLE_SERVICES_INFO_PLIST_ENC }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'

      - name: Decode google-services.json
        run: |
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > android/app/google-services.json

      - name: Decode GoogleService-Info.plist
        run: |
          mkdir -p ios/Runner
          echo "$GOOGLE_SERVICES_INFO_PLIST" | base64 --decode > ios/Runner/GoogleService-Info.plist
          

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --coverage


